version: "2"

services:
  cards-database:
    image: postgres:11
    volumes:
      - .tools/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=cards
      - POSTGRES_PASSWORD=cards
      - POSTGRES_DB=cards

  app:
    extends:
      file: docker-compose.build.yml
      service: gradle
    ports:
      - 8080:8080
    command: bootRun
    env_file: .env
    links:
      - cards-database